kick-player-message: "[é‡æ–°å•Ÿå‹•ç³»çµ±] ä¼ºæœå™¨å°šæœªæº–å‚™å®Œæˆ,è«‹ç¨å¾Œåœ¨è©¦..."
restart: "[é‡æ–°å•Ÿå‹•ç³»çµ±] é–‹å§‹é‡æ–°å•Ÿå‹•..."
server-not-players: "[é‡æ–°å•Ÿå‹•ç³»çµ±] ç•¶å‰ä¼ºæœå™¨ä¸¦ç„¡ä»»ä½•ç©å®¶,ç„¡æ³•ä½¿ç”¨æœ¬ç³»çµ±é‡æ–°å•Ÿå‹•"
shutdown-delay: 10
restart-delay: 10
restart-server: "server1"
wait-server: "wait"

restart-tps-lower-limit: 8
restart-tps-lower-message: "[é‡æ–°å•Ÿå‹•ç³»çµ±] åµæ¸¬åˆ°ä¼ºæœå™¨å¡é “,ä¼ºæœå™¨å°‡è‡ªå‹•é‡æ–°å•Ÿå‹•"

restart-time:
  day: 19
  minute: 0

socket:
  host: "127.0.0.1"
  port: 48765
  timeout: 10000

discord-webhook:
  webhook-url: "https://discord.com/api/webhooks/980508098169032805/DqrCZzOCuWnKF-U8c0H84o4OXDdg2-BXkTLCQ0p6YaNiHKi-v5d8IqBFd2lJa1RZuy0N"
  username: "é‡æ–°å•Ÿå‹•æ©Ÿå™¨äºº"
  avatar-url: "https://cdn.discordapp.com/attachments/879396912745291820/893666032366010420/019.png"
  content: ""
  title: "ğŸ› ï¸ä¼ºæœå™¨é‡æ–°å•Ÿå‹•ğŸ› ï¸"
  description: "**åˆ†æµä¸€ æ­£åœ¨é‡æ–°å•Ÿå‹•ä¸­...**"
  image: "https://cdn.discordapp.com/attachments/879396912745291820/893374136217370694/1.png"
  thumbnail: "https://cdn.discordapp.com/attachments/879396912745291820/893665834587795466/010.png"
  footer-message: "{reason} â€¢ {time}"
  reason-use-command: "äººå·¥åŸ·è¡Œé‡æ–°å•Ÿå‹•"
  reason-time: "å®šæ™‚é‡æ–°å•Ÿå‹•"
  reason-tps-limit: "ä¼ºæœå™¨å¡é “é‡æ–°å•Ÿå‹•"
  footer-image: "https://cdn.discordapp.com/attachments/879396912745291820/893665729650503720/01.png"
